export function generateMarkdown(report) {
  const { repoPath, structure, hotspots, dependencies, complexity, generatedAt } = report;
  const repoName = repoPath.split('/').pop();
  const date = new Date(generatedAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const lines = [];

  lines.push(`# ${repoName} — Codebase Map`);
  lines.push('');
  lines.push(`> Auto-generated by [repo-map](https://github.com/NickCirv/repo-map) on ${date}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Quick Stats
  lines.push('## Quick Stats');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Files | ${structure.totalFiles.toLocaleString()} |`);
  lines.push(`| Total LOC | ${structure.totalLoc.toLocaleString()} |`);
  lines.push(`| Languages | ${structure.languages.slice(0, 5).join(', ') || 'n/a'} |`);
  lines.push(`| Last Commit | ${hotspots.lastCommit} |`);
  lines.push(`| Contributors | ${hotspots.contributorCount} |`);
  if (dependencies.type !== 'unknown') {
    lines.push(`| Package Manager | ${dependencies.type} |`);
    lines.push(`| Direct Dependencies | ${dependencies.totalDirect} |`);
    lines.push(`| Dev Dependencies | ${dependencies.totalDev} |`);
  }
  lines.push('');

  // Architecture Overview
  lines.push('## Architecture Overview');
  lines.push('');

  if (structure.entryPoints.length > 0) {
    lines.push('**Entry Points:**');
    for (const ep of structure.entryPoints) {
      lines.push(`- \`${ep}\``);
    }
    lines.push('');
  }

  if (structure.configFiles.length > 0) {
    lines.push('**Config Files:**');
    for (const cf of structure.configFiles.slice(0, 8)) {
      lines.push(`- \`${cf}\``);
    }
    lines.push('');
  }

  if (structure.testDirs.length > 0) {
    lines.push(`**Test Directories:** ${structure.testDirs.map(d => `\`${d}\``).join(', ')}`);
    lines.push('');
  }

  if (structure.ciFiles.length > 0) {
    lines.push(`**CI/Build:** ${structure.ciFiles.map(f => `\`${f}\``).join(', ')}`);
    lines.push('');
  }

  lines.push('**Directory Structure:**');
  lines.push('');
  lines.push('```');
  lines.push(repoPath.split('/').pop() + '/');
  lines.push(structure.tree || '(empty)');
  lines.push('```');
  lines.push('');

  // Key Files
  lines.push('## Key Files (Read These First)');
  lines.push('');
  lines.push('Ranked by: change frequency × file size × import depth');
  lines.push('');
  lines.push('| # | File | LOC | Imports | Functions |');
  lines.push('|---|------|-----|---------|-----------|');
  for (let i = 0; i < complexity.keyFiles.length; i++) {
    const f = complexity.keyFiles[i];
    const role = f.isEntry ? ' _(entry point)_' : f.isConfig ? ' _(config)_' : '';
    lines.push(`| ${i + 1} | \`${f.relativePath}\`${role} | ${f.loc} | ${f.importCount} | ${f.functionCount} |`);
  }
  lines.push('');

  // Change Hotspots
  if (hotspots.hotspots.length > 0) {
    lines.push('## Change Hotspots (Most Volatile)');
    lines.push('');
    lines.push('Most frequently modified files in the last 100 commits.');
    lines.push('');
    lines.push('| File | Changes | Note |');
    lines.push('|------|---------|------|');
    for (const h of hotspots.hotspots) {
      const note = h.count > 20 ? 'Critical path or high churn — review carefully' : '';
      lines.push(`| \`${h.file}\` | ${h.count} | ${note} |`);
    }
    lines.push('');
  }

  // Dependencies
  if (dependencies.type !== 'unknown' && dependencies.direct.length > 0) {
    lines.push('## Dependency Map');
    lines.push('');
    lines.push(`**Package manager:** ${dependencies.type}`);
    lines.push('');

    if (dependencies.direct.length > 0) {
      lines.push('**Direct Dependencies:**');
      lines.push('');
      lines.push('| Package | Version | Flag |');
      lines.push('|---------|---------|------|');
      for (const dep of dependencies.direct.slice(0, 20)) {
        const flag = dep.flagged ? '⚠ old major version' : '';
        lines.push(`| \`${dep.name}\` | \`${dep.version}\` | ${flag} |`);
      }
      lines.push('');
    }

    if (dependencies.dev.length > 0) {
      lines.push(`**Dev Dependencies:** ${dependencies.dev.length} packages`);
      lines.push('');
      const devNames = dependencies.dev.slice(0, 10).map(d => `\`${d.name}\``).join(', ');
      lines.push(devNames + (dependencies.dev.length > 10 ? `, _+${dependencies.dev.length - 10} more_` : ''));
      lines.push('');
    }
  }

  // Complexity Warnings
  if (complexity.warnings.length > 0) {
    lines.push('## Complexity Warnings');
    lines.push('');
    for (const w of complexity.warnings) {
      const icon = w.severity === 'high' ? '🔴' : w.severity === 'medium' ? '⚠' : 'ℹ';
      lines.push(`- ${icon} \`${w.file}\` — ${w.message}`);
    }
    lines.push('');
  }

  // Start Here Path
  if (complexity.startHere.length > 0) {
    lines.push('## Start Here Path');
    lines.push('');
    lines.push('Read these files in order to understand the codebase:');
    lines.push('');
    for (let i = 0; i < complexity.startHere.length; i++) {
      lines.push(`${i + 1}. \`${complexity.startHere[i]}\``);
    }
    lines.push('');
  }

  // Top Contributors
  if (hotspots.contributors && hotspots.contributors.length > 0) {
    lines.push('## Top Contributors');
    lines.push('');
    for (const c of hotspots.contributors) {
      lines.push(`- **${c.name}** — ${c.commits} commits`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('_Generated by [repo-map](https://github.com/NickCirv/repo-map) — Understand any codebase in 5 minutes._');

  return lines.join('\n');
}
